import fs from 'node:fs/promises'

const date = new Date()
const lastUpdate = `${date.getFullYear()} / ${date.getMonth() + 1} / ${date.getDate()}`
const yearCopyright = date.getFullYear()

const content = /* ts */ `// Generated by script/meta.ts

export const lastUpdate = '${lastUpdate}'
export const yearCopyright = ${yearCopyright}
`

await fs.writeFile('src/meta.g.ts', content, 'utf8')
